# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080


# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://10.0.3.5:36895/wop_sit?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: wop_sit
      password: wRbQvStlyiHy1PS

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.phenom.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml




