# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080


# Spring配置
spring:
  profiles:
    active: sit


# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.phenom.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 开启控制台打印日志
    mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



